apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-spa
  labels:
    app: client-spa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-spa
  template:
    metadata:
      labels:
        app: client-spa
    spec:
      containers:
      - name: client-spa
        image: financemanager-client-spa:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: client-spa
spec:
  selector:
    app: client-spa
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: LoadBalancer
