apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-docker-pv
  labels:
    app: mongodb
    type: docker-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: docker-volume
  hostPath:
    path: /var/lib/docker/volumes/financemanager_mongodb-data/_data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-docker-pv
  labels:
    app: postgres
    type: docker-volume
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: docker-volume
  hostPath:
    path: /var/lib/docker/volumes/financemanager_postgres-data/_data
    type: DirectoryOrCreate
