apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  KEYCLOAK_ADMIN: YWRtaW4=  # admin
  KEYCLOAK_ADMIN_PASSWORD: YWRtaW4=  # admin
  KEYCLOAK_CLIENT_SECRET: aWNiMlh6Q1JXRnZtVGluRmNmRXZHdWM1MWNBUGTWQVK=  # icb2XzCRWFvmTinFcfEvGuc51cAPkpAY
