apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: finance-manager

resources:
  - namespace.yaml
  
  # Docker Volumes PersistentVolumes
  - docker-volumes-pv.yaml
  
  # Secrets and ConfigMaps
  - postgres-secret.yaml
  - keycloak-secret.yaml
  - app-configmap.yaml
  - keycloak-configmap.yaml
  
  # Infrastructure Services
  - postgres.yaml
  - mongodb.yaml
  - keycloak.yaml
  
  # Application Services
  - user-service.yaml
  - finance-service.yaml
  - resource-server.yaml
  - client-spa.yaml

labels:
  - pairs:
      app.kubernetes.io/name: finance-manager
      app.kubernetes.io/instance: finance-manager-stack
      app.kubernetes.io/part-of: finance-manager-application
      app.kubernetes.io/managed-by: kustomize
      project: finance-manager
      environment: development

commonAnnotations:
  com.docker.compose.project: finance-manager
  app.kubernetes.io/version: "1.0.0"

namespace: finance-manager

# Images configuration
images:
  - name: financemanager-user-service
    newTag: latest
  - name: financemanager-finance-service
    newTag: latest
  - name: financemanager-resource-server
    newTag: latest
  - name: financemanager-client-spa
    newTag: latest
