apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_DB: a2V5Y2xvYWs=  # keycloak
  POSTGRES_USER: a2V5Y2xvYWs=  # keycloak  
  POSTGRES_PASSWORD: a2V5Y2xvYWs=  # keycloak
